version: '3'

services:
  app_server:
    build:
      context: .
      dockerfile: app_server.dockerfile
    container_name: app_server
    image: app_server_image
    volumes:
      - ./disk/etc/nginx_hsm.conf:/etc/nginx/nginx.conf
      - ./disk/etc/softhsm2.conf:/etc/softhsm/softhsm2.conf
      - ./disk/keystore:/app/keystore
      - ./disk/apps/ngx_http_hsm_service_module.so:/usr/lib/nginx/modules/ngx_http_hsm_service_module.so
      - ./disk/apps/index.html:/usr/share/nginx/html/index.html

  web_server:
    build:
      context: .
      dockerfile: web_server.dockerfile
    container_name: web_server
    image: web_server_image
    #restart: on-failure
    depends_on:
      app_server:
        condition: service_started
    links:
      - app_server
    ports:
      - 4443:4443
    volumes:
      - ./disk/etc/nginx_web.conf:/etc/nginx/nginx.conf
      - ./disk/etc/openssl.cnf:/etc/ssl/openssl.cnf
      - ./disk/apps/cb_engine.so:/usr/lib/x86_64-linux-gnu/engines-1.1/cb_engine.so
      - ./disk/etc/certs:/etc/certs
      - ./disk/apps/index.html:/usr/share/nginx/html/index.html
    environment:
      - CB_ENGINE_URL=http://app_server/hsm
